name: phpstan
on: [ push, workflow_dispatch ]
jobs:
  phpstan_7_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan Static Analysis 7.3
        uses: php-actions/phpstan@v2
        with:
          command: analyse --debug
          configuration: phpstan.neon
          php_version: 7.3

  phpstan_7_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan Static Analysis 7.4
        uses: php-actions/phpstan@v2
        with:
          command: analyse --debug
          configuration: phpstan.neon
          php_version: 7.4

