name: phpstan
on: [ push, workflow_dispatch ]
jobs:
  phpstan_7_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHPStan Static Analysis 7.3
      - uses: php-actions/phpstan@v2
      - uses: php-actions/composer@v5
        with:
          command: analyse --debug
          configuration: phpstan.neon
          php_version: 7.3

  phpstan_7_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHPStan Static Analysis 7.3
      - uses: php-actions/phpstan@v2
      - uses: php-actions/composer@v5
        with:
          command: analyse --debug
          configuration: phpstan.neon
          php_version: 7.4

